apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-serviceaccount
      containers:
        - name: slackwatch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            {{- range $key, $val := .Values.customEnv }}
              {{- if $val.fromSecret.enabled }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.fromSecret.secretName }}
                  key: {{ $val.fromSecret.key }}
              {{- else }}
            - name: {{ $key }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}-config
