[book]
authors = ["Jacob Morgan"]
language = "en"
multilingual = false
src = "docs/"
title = "Slackwatch Documentation"

[rust]
edition = "2021"



[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/slackspace-io/slackwatch"
highlight-code = true

[output.html.redirect]
"index.yaml" = "https://raw.githubusercontent.com/slackspace-io/slackwatch/gh-pages/index.yaml"
