[book]
authors = ["Jacob Morgan"]
language = "en"
multilingual = false
src = "docs/"
title = "Slackwatch Documentation"

[rust]
edition = "2021"

[build]
build-dir = "site/book"


[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/slackspace-io/slackwatch"
highlight-code = true

