[application]

# App (Project) Name
name = "Slackwatch"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "slackwatch"

# resource (public) file folder
asset_dir = "assets"

address = "0.0.0.0"

[web.app]

# HTML title tag content
title = "Slackwatch"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["/style.css"]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = ["/style.css"]

# Javascript code file
script = []

[server]
addr = "0.0.0.0"

[server.app]
addr = "0.0.0.0"
