replicaCount: 1
namespace: slackwatch

image:
  repository: ghcr.io/slackspace-io/slackwatch  # Assuming this image is accessible as a placeholder
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  labels: {}
  ingressClassName: ""
  paths:
    - /
  pathType: Prefix
  extraPaths: []
  https: false
  annotations: {}
  tls: []
  hosts:
    - test.slackwatch.default # Placeholder domain

config:
  system:
    #default schedule is every 2 hours
    schedule: "0 0 */2 * *"
    data_dir: "/app/slackwatch/data"

