apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slackwatch
  template:
    metadata:
      labels:
        app: slackwatch
    spec:
      serviceAccountName: slackwatch-backend
      containers:
      - name: slackwatch
        image: ghcr.io/slackspace-io/slackwatch:dev
        ports:
        - containerPort: 8080
        env:
        - name: SLACKWATCH_NOTIFICATIONS.NTFY.TOKEN
          valueFrom:
            secretKeyRef:
              name: ntfy-token
              key: token
        - name: fleet-slack-house-token
          valueFrom:
            secretKeyRef:
              name: fleet-slack-house-token
              key: token
        volumeMounts:
          - name: config-volume
            mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: slackwatch-config
