apiVersion: apps/v1
kind: Deployment
metadata:
  name: slackwatch-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slackwatch-rs
  template:
    metadata:
      labels:
        app: slackwatch-rs
    spec:
      serviceAccountName: slackwatch-backend
      containers:
      - name: slackwatch-rs
        image: ghcr.io/slackspace-io/slackwatch-rs:latest
        ports:
        - containerPort: 8080
        env:
        - name: NTFY_TOKEN
          valueFrom:
            secretKeyRef:
              name: ntfy-token
              key: token
        - name: fleet-slack-house-token
          valueFrom:
            secretKeyRef:
              name: fleet-slack-house-token
              key: token
        volumeMounts:
          - name: config-volume
            mountPath: /app/config/
      volumes:
      - name: config-volume
        configMap:
          name: slackwatch-config
