apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - cluster-role.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: slackwatch-config
    files:
      - ./config/config.toml
