name: Build and Push Rust Docker Image

on:
  push:
    branches:
      - main
      - rust
    paths:
      - 'rust/**'
      - '.github/workflows/rust.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./rust
          file: ./rust/Dockerfile
          push: true
          tags: ghcr.io/slackspace-io/slackwatch-rs:latest,ghcr.io/slackspace-io/slackwatch-rs:dev,ghcr.io/slackspace-io/slackwatch-rs:${{ github.sha }}
